services:
  PostgreSQL:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: tinkoff
      POSTGRES_PASSWORD: he_is_the_only_one
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  RabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - PostgreSQL
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=tinkoff
      - --password=he_is_the_only_one
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

networks:
  backend:

volumes:
  postgres-data:
  rabbitmq-data: