/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import java.beans.ConstructorProperties;
import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Chats;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatsRecord extends UpdatableRecordImpl<ChatsRecord> implements Record3<Long, LocalDateTime, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chats.id</code>.
     */
    public void setId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chats.id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.chats.created_date</code>.
     */
    public void setCreatedDate(@NotNull LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chats.created_date</code>.
     */
    @NotNull
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.chats.last_call_date</code>.
     */
    public void setLastCallDate(@NotNull LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.chats.last_call_date</code>.
     */
    @NotNull
    public LocalDate getLastCallDate() {
        return (LocalDate) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, LocalDateTime, LocalDate> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, LocalDateTime, LocalDate> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Chats.CHATS.ID;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field2() {
        return Chats.CHATS.CREATED_DATE;
    }

    @Override
    @NotNull
    public Field<LocalDate> field3() {
        return Chats.CHATS.LAST_CALL_DATE;
    }

    @Override
    @NotNull
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public LocalDateTime component2() {
        return getCreatedDate();
    }

    @Override
    @NotNull
    public LocalDate component3() {
        return getLastCallDate();
    }

    @Override
    @NotNull
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public LocalDateTime value2() {
        return getCreatedDate();
    }

    @Override
    @NotNull
    public LocalDate value3() {
        return getLastCallDate();
    }

    @Override
    @NotNull
    public ChatsRecord value1(@NotNull Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public ChatsRecord value2(@NotNull LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    @NotNull
    public ChatsRecord value3(@NotNull LocalDate value) {
        setLastCallDate(value);
        return this;
    }

    @Override
    @NotNull
    public ChatsRecord values(@NotNull Long value1, @NotNull LocalDateTime value2, @NotNull LocalDate value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatsRecord
     */
    public ChatsRecord() {
        super(Chats.CHATS);
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    @ConstructorProperties({ "id", "createdDate", "lastCallDate" })
    public ChatsRecord(@NotNull Long id, @NotNull LocalDateTime createdDate, @NotNull LocalDate lastCallDate) {
        super(Chats.CHATS);

        setId(id);
        setCreatedDate(createdDate);
        setLastCallDate(lastCallDate);
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    public ChatsRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.Chats value) {
        super(Chats.CHATS);

        if (value != null) {
            setId(value.getId());
            setCreatedDate(value.getCreatedDate());
            setLastCallDate(value.getLastCallDate());
        }
    }
}
