/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import java.beans.ConstructorProperties;
import java.time.LocalDate;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Domains;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DomainsRecord extends UpdatableRecordImpl<DomainsRecord> implements Record3<Long, String, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.domains.id</code>.
     */
    public void setId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.domains.id</code>.
     */
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.domains.name</code>.
     */
    public void setName(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.domains.name</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.domains.created_date</code>.
     */
    public void setCreatedDate(@NotNull LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.domains.created_date</code>.
     */
    @NotNull
    public LocalDate getCreatedDate() {
        return (LocalDate) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, String, LocalDate> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, String, LocalDate> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Domains.DOMAINS.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Domains.DOMAINS.NAME;
    }

    @Override
    @NotNull
    public Field<LocalDate> field3() {
        return Domains.DOMAINS.CREATED_DATE;
    }

    @Override
    @NotNull
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public String component2() {
        return getName();
    }

    @Override
    @NotNull
    public LocalDate component3() {
        return getCreatedDate();
    }

    @Override
    @NotNull
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public String value2() {
        return getName();
    }

    @Override
    @NotNull
    public LocalDate value3() {
        return getCreatedDate();
    }

    @Override
    @NotNull
    public DomainsRecord value1(@NotNull Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public DomainsRecord value2(@NotNull String value) {
        setName(value);
        return this;
    }

    @Override
    @NotNull
    public DomainsRecord value3(@NotNull LocalDate value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    @NotNull
    public DomainsRecord values(@NotNull Long value1, @NotNull String value2, @NotNull LocalDate value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DomainsRecord
     */
    public DomainsRecord() {
        super(Domains.DOMAINS);
    }

    /**
     * Create a detached, initialised DomainsRecord
     */
    @ConstructorProperties({ "id", "name", "createdDate" })
    public DomainsRecord(@NotNull Long id, @NotNull String name, @NotNull LocalDate createdDate) {
        super(Domains.DOMAINS);

        setId(id);
        setName(name);
        setCreatedDate(createdDate);
    }

    /**
     * Create a detached, initialised DomainsRecord
     */
    public DomainsRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.Domains value) {
        super(Domains.DOMAINS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setCreatedDate(value.getCreatedDate());
        }
    }
}
