/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chats implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private LocalDateTime createdDate;
    private LocalDate lastCallDate;

    public Chats() {}

    public Chats(Chats value) {
        this.id = value.id;
        this.createdDate = value.createdDate;
        this.lastCallDate = value.lastCallDate;
    }

    @ConstructorProperties({ "id", "createdDate", "lastCallDate" })
    public Chats(
        @NotNull Long id,
        @NotNull LocalDateTime createdDate,
        @NotNull LocalDate lastCallDate
    ) {
        this.id = id;
        this.createdDate = createdDate;
        this.lastCallDate = lastCallDate;
    }

    /**
     * Getter for <code>public.chats.id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.chats.id</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.chats.created_date</code>.
     */
    @NotNull
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>public.chats.created_date</code>.
     */
    public void setCreatedDate(@NotNull LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>public.chats.last_call_date</code>.
     */
    @NotNull
    public LocalDate getLastCallDate() {
        return this.lastCallDate;
    }

    /**
     * Setter for <code>public.chats.last_call_date</code>.
     */
    public void setLastCallDate(@NotNull LocalDate lastCallDate) {
        this.lastCallDate = lastCallDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Chats other = (Chats) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.lastCallDate == null) {
            if (other.lastCallDate != null)
                return false;
        }
        else if (!this.lastCallDate.equals(other.lastCallDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.lastCallDate == null) ? 0 : this.lastCallDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Chats (");

        sb.append(id);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(lastCallDate);

        sb.append(")");
        return sb.toString();
    }
}
