/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq;


import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.ChatLink;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Chats;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Databasechangeloglock;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Domains;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Links;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.ChatLinkRecord;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.ChatsRecord;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.DatabasechangeloglockRecord;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.DomainsRecord;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.LinksRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatLinkRecord> CHAT_LINK_PKEY = Internal.createUniqueKey(ChatLink.CHAT_LINK, DSL.name("chat_link_pkey"), new TableField[] { ChatLink.CHAT_LINK.CHAT_ID, ChatLink.CHAT_LINK.LINK_ID }, true);
    public static final UniqueKey<ChatsRecord> CHATS_PKEY = Internal.createUniqueKey(Chats.CHATS, DSL.name("chats_pkey"), new TableField[] { Chats.CHATS.ID }, true);
    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("databasechangeloglock_pkey"), new TableField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
    public static final UniqueKey<DomainsRecord> DOMAINS_NAME_KEY = Internal.createUniqueKey(Domains.DOMAINS, DSL.name("domains_name_key"), new TableField[] { Domains.DOMAINS.NAME }, true);
    public static final UniqueKey<DomainsRecord> DOMAINS_PKEY = Internal.createUniqueKey(Domains.DOMAINS, DSL.name("domains_pkey"), new TableField[] { Domains.DOMAINS.ID }, true);
    public static final UniqueKey<LinksRecord> LINKS_LINK_KEY = Internal.createUniqueKey(Links.LINKS, DSL.name("links_link_key"), new TableField[] { Links.LINKS.LINK }, true);
    public static final UniqueKey<LinksRecord> LINKS_PKEY = Internal.createUniqueKey(Links.LINKS, DSL.name("links_pkey"), new TableField[] { Links.LINKS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatLinkRecord, ChatsRecord> CHAT_LINK__CHAT_LINK_CHAT_ID_FKEY = Internal.createForeignKey(ChatLink.CHAT_LINK, DSL.name("chat_link_chat_id_fkey"), new TableField[] { ChatLink.CHAT_LINK.CHAT_ID }, Keys.CHATS_PKEY, new TableField[] { Chats.CHATS.ID }, true);
    public static final ForeignKey<ChatLinkRecord, LinksRecord> CHAT_LINK__CHAT_LINK_LINK_ID_FKEY = Internal.createForeignKey(ChatLink.CHAT_LINK, DSL.name("chat_link_link_id_fkey"), new TableField[] { ChatLink.CHAT_LINK.LINK_ID }, Keys.LINKS_PKEY, new TableField[] { Links.LINKS.ID }, true);
    public static final ForeignKey<LinksRecord, DomainsRecord> LINKS__LINKS_DOMAIN_ID_FKEY = Internal.createForeignKey(Links.LINKS, DSL.name("links_domain_id_fkey"), new TableField[] { Links.LINKS.DOMAIN_ID }, Keys.DOMAINS_PKEY, new TableField[] { Domains.DOMAINS.ID }, true);
}
