name: Bot CI
on:
  push:
    paths:
      - 'bot/**'
  pull_request:
    paths:
      - 'bot/**'

env:
  ARTEFACT_NAME: bot.jar
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/tg-bot-for-tracking-links:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn package -pl bot -am

      - uses: actions/upload-artifact@v3
        with:
          path: bot/target/bot-1.0-SNAPSHOT.jar
          name: $ARTEFACT_NAME
          retention-days: 1

      - name: Run checkstyle
        run: mvn -pl bot -am checkstyle:check

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t $IMAGE_NAME -f bot/Dockerfile .

      - name: Push image
        run: docker push $IMAGE_NAME
