name: Bot CI

on:
  push:
    branches:
      - 'master'
      - 'hw8'
  pull_request:
    branches:
      - 'hw8'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn package -pl bot -am

      - uses: actions/download-artifact@v2
        with:
          name: bot.jar
          path: target/bot-1.0-SNAPSHOT.jar

      - name: Build bot image
        run: docker build -t tg-bot-for-tracking-links:latest .