name: Bot CI

on:
  push:
    branches:
      - 'master'
      - 'hw8'
  pull_request:
    branches:
      - 'hw8'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn package -pl bot -am

      - uses: actions/upload-artifact@v3
        with:
          path: bot/target/bot-1.0-SNAPSHOT.jar
          name: bot.jar
          retention-days: 1

      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tg-bot-for-tracking-links:latest -f bot/Dockerfile .

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tg-bot-for-tracking-links:latest