name: Scrapper CI

on:
  push:
    branches:
      - 'master'
      - 'Homework9'
    pull_request:
      branches:
        - 'Homework9'
        - 'master'
        - 'hw8'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package -pl scrapper -am

      - uses: actions/upload-artifact@v3
        with:
          path: scrapper/target/scrapper-1.0-SNAPSHOT.jar
          name: scrapper.jar
          retention-days: 1

      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/scrapper-links:latest -f scrapper/Dockerfile .

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/scrapper-links:latest

      - name: Run checkstyle
        run: mvn -pl scrapper -am checkstyle:check