name: Scrapper CI

on:
  push:
    paths:
      - 'scrapper/**'
  pull_request:
    paths:
      - 'scrapper/**'

env:
  ARTEFACT_NAME: scrapper.jar
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/scrapper-links:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package -pl scrapper -am

      - uses: actions/upload-artifact@v3
        with:
          path: scrapper/target/scrapper-1.0-SNAPSHOT.jar
          name: $ARTEFACT_NAME
          retention-days: 1

      - name: Run checkstyle
        run: mvn -pl scrapper -am checkstyle:check

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t $IMAGE_NAME -f scrapper/Dockerfile .

      - name: Push image
        run: docker push $IMAGE_NAME
